version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'friday'
      time: '10:00'
    groups:
      npm-dependencies:
        patterns:
          - "*"
    assignees:
      - "mitchfen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'friday'
      time: '10:00'
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - "mitchfen"
