events { }
http {
    include mime.types;


    server {
        listen 80;
        location / {
            root /usr/local/webapp/nginx/html;
            try_files $uri $uri/ =404;
        }
        location ~ /\.well-known {
            root /usr/local/webapp/nginx/html;
        }
    }
}
