name: Cleanup

on:
  pull_request:
    types:
      - "closed"

jobs:
  close_staging:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    name: Close staging environment ${{ github.event.number }}
    steps:
      - name: Close staging environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}
          action: "close"

  cleanup:
    name: Cleanup untagged container images
    runs-on: ubuntu-latest
    steps:
      - uses: mitchfen/cleanup-untagged-container-images@main
        with:
          username: 'mitchfen'
          container-name: 'mitchfen.xyz'
          token: ${{ secrets.GHCR_TOKEN }}
