name: Deploy Azure static site

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./build
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "mitchfen.xyz"
      url: https://mitchfen.xyz

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: "" # Leave empty, app is already built
          skip_app_build: true
