name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./build
          retention-days: 1

  deploy-static-site:
    runs-on: ubuntu-latest
    needs: "npm-build"
    environment:
      name: "mitchfen.xyz"
      url: https://mitchfen.xyz

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: "" # Leave empty, app is already built
          skip_app_build: true

  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker login
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker login
        uses: docker/login-action@master
        with:
          registry: docker.io
          username: mitchfen
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          tags: docker.io/mitchfen/mitchfen.xyz:latest
