name: Publish container

on:
  workflow_run:
    workflows: ['Deploy Azure static site']
    branches: ['main']
    types: [completed]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publishContainer:
    runs-on: ubuntu-latest
    environment:
      name: container-deployment
      url: 'https://mitchfen-container-app.livelyisland-a831ae75.canadacentral.azurecontainerapps.io/'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker login
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
