
name: Deploy staging

on:
  workflow_dispatch:
  push:
   branches:
    - feat/migrate-to-blazor

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          dotnet workload install wasm-tools
          ./build.sh Publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  deploy-static-site:
    name: Deploy static site
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "mitchfen.xyz-staging"
      url: "https://calm-flower-0acda890f.1.azurestaticapps.net"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: output
          path: output

      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_SITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "output"
          output_location: "" # Leave empty, app is already built
          skip_app_build: true
